//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isp_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Head_TB
    {
        public Account_Head_TB()
        {
            this.ExpenseTBs = new HashSet<ExpenseTB>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ExpenseTB> ExpenseTBs { get; set; }
    }
}
