//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isp_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public Nullable<int> Blood_Group_Id { get; set; }
        public string National_Id { get; set; }
        public string Occupation { get; set; }
        public string Address { get; set; }
        public Nullable<double> Monthly_Amount { get; set; }
        public string IP_Address { get; set; }
        public string Connection_Date { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public Nullable<int> Route { get; set; }
        public Nullable<int> Package { get; set; }
        public string Discount { get; set; }
        public Nullable<bool> Image { get; set; }
        public Nullable<int> Voter_Id { get; set; }
    
        public virtual Blood_Group_TB Blood_Group_TB { get; set; }
        public virtual Client_Status Client_Status { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual PackageTB PackageTB { get; set; }
        public virtual RouteTB RouteTB { get; set; }
    }
}
