//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isp_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseTB
    {
        public int Id { get; set; }
        public Nullable<int> AccountHead_Id { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Amount_Details { get; set; }
        public string Ref { get; set; }
    
        public virtual Account_Head_TB Account_Head_TB { get; set; }
    }
}
