//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isp_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account_Head_TB> Account_Head_TB { get; set; }
        public DbSet<Blood_Group_TB> Blood_Group_TB { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Client_Status> Client_Status { get; set; }
        public DbSet<ExpenseTB> ExpenseTBs { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<PackageTB> PackageTBs { get; set; }
        public DbSet<RouteTB> RouteTBs { get; set; }
        public DbSet<StatusTB> StatusTBs { get; set; }
        public DbSet<User_StatusTB> User_StatusTB { get; set; }
        public DbSet<UserTB> UserTBs { get; set; }
        public DbSet<UsertypeTB> UsertypeTBs { get; set; }
    }
}
