//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isp_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTB
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public string National_Id { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Image { get; set; }
        public Nullable<bool> Voter_Id_Image { get; set; }
        public Nullable<int> UserStatus_Id { get; set; }
        public Nullable<int> UserType_Id { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual User_StatusTB User_StatusTB { get; set; }
        public virtual UsertypeTB UsertypeTB { get; set; }
    }
}
